name: Offboard Project

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: "Project name prefix used during onboarding"
        required: true
      team_name:
        description: "Team name prefix used during onboarding"
        required: true

jobs:
  offboard:
    defaults:
      run:
        working-directory: ./hcpt

    name: Offboard ${{ inputs.project_name }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run offboarding script
        env:
          TFE_TOKEN: ${{ secrets.TFE_TOKEN }}
          TFE_ORGANIZATION: ${{ secrets.TFE_ORGANIZATION }}
          TFE_HOSTNAME: ${{ secrets.TFE_HOSTNAME }}
        run: |
          python offboard.py \
            --project-name ${{ inputs.project_name }} \
            --team-name ${{ inputs.team_name }} \
            --yes
